/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FinishingRouteImport } from './routes/finishing'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as IHandleRouteImport } from './routes/i.$handle'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminXpRouteImport } from './routes/admin/xp'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminReviewRouteImport } from './routes/admin/review'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLevelsRouteImport } from './routes/admin/levels'
import { Route as AdminDailyRouteImport } from './routes/admin/daily'
import { Route as ApiAdminXpConfigRouteImport } from './routes/api/admin/xp-config'
import { Route as ApiAdminTagsRouteImport } from './routes/api/admin/tags'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminPingRouteImport } from './routes/api/admin/ping'
import { Route as ApiAdminLevelsRouteImport } from './routes/api/admin/levels'
import { Route as ApiAdminDailyRouteImport } from './routes/api/admin/daily'
import { Route as ApiAdminBarsRouteImport } from './routes/api/admin/bars'
import { Route as ApiAdminArtistsRouteImport } from './routes/api/admin/artists'
import { Route as ApiAdminSubmissionsIdRouteImport } from './routes/api/admin/submissions.$id'
import { Route as ApiAdminSongsIdRouteImport } from './routes/api/admin/songs.$id'
import { Route as ApiAdminSearchTracksRouteImport } from './routes/api/admin/search.tracks'
import { Route as ApiAdminSearchArtistsRouteImport } from './routes/api/admin/search.artists'
import { Route as ApiAdminDailyIdRouteImport } from './routes/api/admin/daily.$id'
import { Route as ApiAdminBarsIdRouteImport } from './routes/api/admin/bars.$id'
import { Route as ApiAdminArtistsIdRouteImport } from './routes/api/admin/artists.$id'
import { Route as ApiAdminSearchTrackIdRouteImport } from './routes/api/admin/search.track.$id'
import { Route as ApiAdminArtistsIdTagsRouteImport } from './routes/api/admin/artists.$id.tags'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishingRoute = FinishingRouteImport.update({
  id: '/finishing',
  path: '/finishing',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IHandleRoute = IHandleRouteImport.update({
  id: '/i/$handle',
  path: '/i/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXpRoute = AdminXpRouteImport.update({
  id: '/admin/xp',
  path: '/admin/xp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLevelsRoute = AdminLevelsRouteImport.update({
  id: '/admin/levels',
  path: '/admin/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailyRoute = AdminDailyRouteImport.update({
  id: '/admin/daily',
  path: '/admin/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminXpConfigRoute = ApiAdminXpConfigRouteImport.update({
  id: '/api/admin/xp-config',
  path: '/api/admin/xp-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTagsRoute = ApiAdminTagsRouteImport.update({
  id: '/api/admin/tags',
  path: '/api/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPingRoute = ApiAdminPingRouteImport.update({
  id: '/api/admin/ping',
  path: '/api/admin/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLevelsRoute = ApiAdminLevelsRouteImport.update({
  id: '/api/admin/levels',
  path: '/api/admin/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDailyRoute = ApiAdminDailyRouteImport.update({
  id: '/api/admin/daily',
  path: '/api/admin/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBarsRoute = ApiAdminBarsRouteImport.update({
  id: '/api/admin/bars',
  path: '/api/admin/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtistsRoute = ApiAdminArtistsRouteImport.update({
  id: '/api/admin/artists',
  path: '/api/admin/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsIdRoute = ApiAdminSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSubmissionsRoute,
} as any)
const ApiAdminSongsIdRoute = ApiAdminSongsIdRouteImport.update({
  id: '/api/admin/songs/$id',
  path: '/api/admin/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSearchTracksRoute = ApiAdminSearchTracksRouteImport.update({
  id: '/api/admin/search/tracks',
  path: '/api/admin/search/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSearchArtistsRoute = ApiAdminSearchArtistsRouteImport.update({
  id: '/api/admin/search/artists',
  path: '/api/admin/search/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDailyIdRoute = ApiAdminDailyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminDailyRoute,
} as any)
const ApiAdminBarsIdRoute = ApiAdminBarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBarsRoute,
} as any)
const ApiAdminArtistsIdRoute = ApiAdminArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminArtistsRoute,
} as any)
const ApiAdminSearchTrackIdRoute = ApiAdminSearchTrackIdRouteImport.update({
  id: '/api/admin/search/track/$id',
  path: '/api/admin/search/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtistsIdTagsRoute = ApiAdminArtistsIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ApiAdminArtistsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/submit': typeof SubmitRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/xp': typeof AdminXpRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$handle': typeof IHandleRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/levels': typeof ApiAdminLevelsRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/xp-config': typeof ApiAdminXpConfigRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/submit': typeof SubmitRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/xp': typeof AdminXpRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$handle': typeof IHandleRoute
  '/u/$handle': typeof UHandleRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/levels': typeof ApiAdminLevelsRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/xp-config': typeof ApiAdminXpConfigRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/submit': typeof SubmitRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/xp': typeof AdminXpRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$handle': typeof IHandleRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/levels': typeof ApiAdminLevelsRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/xp-config': typeof ApiAdminXpConfigRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/finishing'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/submit'
    | '/admin/daily'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/review'
    | '/admin/submissions'
    | '/admin/xp'
    | '/c/$slug'
    | '/i/$handle'
    | '/u/$handle'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/levels'
    | '/api/admin/ping'
    | '/api/admin/submissions'
    | '/api/admin/tags'
    | '/api/admin/xp-config'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/finishing'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/submit'
    | '/admin/daily'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/review'
    | '/admin/submissions'
    | '/admin/xp'
    | '/c/$slug'
    | '/i/$handle'
    | '/u/$handle'
    | '/admin'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/levels'
    | '/api/admin/ping'
    | '/api/admin/submissions'
    | '/api/admin/tags'
    | '/api/admin/xp-config'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/finishing'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/submit'
    | '/admin/daily'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/review'
    | '/admin/submissions'
    | '/admin/xp'
    | '/c/$slug'
    | '/i/$handle'
    | '/u/$handle'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/levels'
    | '/api/admin/ping'
    | '/api/admin/submissions'
    | '/api/admin/tags'
    | '/api/admin/xp-config'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  FinishingRoute: typeof FinishingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  SubmitRoute: typeof SubmitRoute
  AdminDailyRoute: typeof AdminDailyRoute
  AdminLevelsRoute: typeof AdminLevelsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminXpRoute: typeof AdminXpRoute
  CSlugRoute: typeof CSlugRoute
  IHandleRoute: typeof IHandleRoute
  UHandleRoute: typeof UHandleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminArtistsRoute: typeof ApiAdminArtistsRouteWithChildren
  ApiAdminBarsRoute: typeof ApiAdminBarsRouteWithChildren
  ApiAdminDailyRoute: typeof ApiAdminDailyRouteWithChildren
  ApiAdminLevelsRoute: typeof ApiAdminLevelsRoute
  ApiAdminPingRoute: typeof ApiAdminPingRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRouteWithChildren
  ApiAdminTagsRoute: typeof ApiAdminTagsRoute
  ApiAdminXpConfigRoute: typeof ApiAdminXpConfigRoute
  ApiAdminSearchArtistsRoute: typeof ApiAdminSearchArtistsRoute
  ApiAdminSearchTracksRoute: typeof ApiAdminSearchTracksRoute
  ApiAdminSongsIdRoute: typeof ApiAdminSongsIdRoute
  ApiAdminSearchTrackIdRoute: typeof ApiAdminSearchTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finishing': {
      id: '/finishing'
      path: '/finishing'
      fullPath: '/finishing'
      preLoaderRoute: typeof FinishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$handle': {
      id: '/i/$handle'
      path: '/i/$handle'
      fullPath: '/i/$handle'
      preLoaderRoute: typeof IHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/xp': {
      id: '/admin/xp'
      path: '/admin/xp'
      fullPath: '/admin/xp'
      preLoaderRoute: typeof AdminXpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/levels': {
      id: '/admin/levels'
      path: '/admin/levels'
      fullPath: '/admin/levels'
      preLoaderRoute: typeof AdminLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily': {
      id: '/admin/daily'
      path: '/admin/daily'
      fullPath: '/admin/daily'
      preLoaderRoute: typeof AdminDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/xp-config': {
      id: '/api/admin/xp-config'
      path: '/api/admin/xp-config'
      fullPath: '/api/admin/xp-config'
      preLoaderRoute: typeof ApiAdminXpConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tags': {
      id: '/api/admin/tags'
      path: '/api/admin/tags'
      fullPath: '/api/admin/tags'
      preLoaderRoute: typeof ApiAdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ping': {
      id: '/api/admin/ping'
      path: '/api/admin/ping'
      fullPath: '/api/admin/ping'
      preLoaderRoute: typeof ApiAdminPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/levels': {
      id: '/api/admin/levels'
      path: '/api/admin/levels'
      fullPath: '/api/admin/levels'
      preLoaderRoute: typeof ApiAdminLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/daily': {
      id: '/api/admin/daily'
      path: '/api/admin/daily'
      fullPath: '/api/admin/daily'
      preLoaderRoute: typeof ApiAdminDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bars': {
      id: '/api/admin/bars'
      path: '/api/admin/bars'
      fullPath: '/api/admin/bars'
      preLoaderRoute: typeof ApiAdminBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artists': {
      id: '/api/admin/artists'
      path: '/api/admin/artists'
      fullPath: '/api/admin/artists'
      preLoaderRoute: typeof ApiAdminArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions/$id': {
      id: '/api/admin/submissions/$id'
      path: '/$id'
      fullPath: '/api/admin/submissions/$id'
      preLoaderRoute: typeof ApiAdminSubmissionsIdRouteImport
      parentRoute: typeof ApiAdminSubmissionsRoute
    }
    '/api/admin/songs/$id': {
      id: '/api/admin/songs/$id'
      path: '/api/admin/songs/$id'
      fullPath: '/api/admin/songs/$id'
      preLoaderRoute: typeof ApiAdminSongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/search/tracks': {
      id: '/api/admin/search/tracks'
      path: '/api/admin/search/tracks'
      fullPath: '/api/admin/search/tracks'
      preLoaderRoute: typeof ApiAdminSearchTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/search/artists': {
      id: '/api/admin/search/artists'
      path: '/api/admin/search/artists'
      fullPath: '/api/admin/search/artists'
      preLoaderRoute: typeof ApiAdminSearchArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/daily/$id': {
      id: '/api/admin/daily/$id'
      path: '/$id'
      fullPath: '/api/admin/daily/$id'
      preLoaderRoute: typeof ApiAdminDailyIdRouteImport
      parentRoute: typeof ApiAdminDailyRoute
    }
    '/api/admin/bars/$id': {
      id: '/api/admin/bars/$id'
      path: '/$id'
      fullPath: '/api/admin/bars/$id'
      preLoaderRoute: typeof ApiAdminBarsIdRouteImport
      parentRoute: typeof ApiAdminBarsRoute
    }
    '/api/admin/artists/$id': {
      id: '/api/admin/artists/$id'
      path: '/$id'
      fullPath: '/api/admin/artists/$id'
      preLoaderRoute: typeof ApiAdminArtistsIdRouteImport
      parentRoute: typeof ApiAdminArtistsRoute
    }
    '/api/admin/search/track/$id': {
      id: '/api/admin/search/track/$id'
      path: '/api/admin/search/track/$id'
      fullPath: '/api/admin/search/track/$id'
      preLoaderRoute: typeof ApiAdminSearchTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artists/$id/tags': {
      id: '/api/admin/artists/$id/tags'
      path: '/tags'
      fullPath: '/api/admin/artists/$id/tags'
      preLoaderRoute: typeof ApiAdminArtistsIdTagsRouteImport
      parentRoute: typeof ApiAdminArtistsIdRoute
    }
  }
}

interface ApiAdminArtistsIdRouteChildren {
  ApiAdminArtistsIdTagsRoute: typeof ApiAdminArtistsIdTagsRoute
}

const ApiAdminArtistsIdRouteChildren: ApiAdminArtistsIdRouteChildren = {
  ApiAdminArtistsIdTagsRoute: ApiAdminArtistsIdTagsRoute,
}

const ApiAdminArtistsIdRouteWithChildren =
  ApiAdminArtistsIdRoute._addFileChildren(ApiAdminArtistsIdRouteChildren)

interface ApiAdminArtistsRouteChildren {
  ApiAdminArtistsIdRoute: typeof ApiAdminArtistsIdRouteWithChildren
}

const ApiAdminArtistsRouteChildren: ApiAdminArtistsRouteChildren = {
  ApiAdminArtistsIdRoute: ApiAdminArtistsIdRouteWithChildren,
}

const ApiAdminArtistsRouteWithChildren = ApiAdminArtistsRoute._addFileChildren(
  ApiAdminArtistsRouteChildren,
)

interface ApiAdminBarsRouteChildren {
  ApiAdminBarsIdRoute: typeof ApiAdminBarsIdRoute
}

const ApiAdminBarsRouteChildren: ApiAdminBarsRouteChildren = {
  ApiAdminBarsIdRoute: ApiAdminBarsIdRoute,
}

const ApiAdminBarsRouteWithChildren = ApiAdminBarsRoute._addFileChildren(
  ApiAdminBarsRouteChildren,
)

interface ApiAdminDailyRouteChildren {
  ApiAdminDailyIdRoute: typeof ApiAdminDailyIdRoute
}

const ApiAdminDailyRouteChildren: ApiAdminDailyRouteChildren = {
  ApiAdminDailyIdRoute: ApiAdminDailyIdRoute,
}

const ApiAdminDailyRouteWithChildren = ApiAdminDailyRoute._addFileChildren(
  ApiAdminDailyRouteChildren,
)

interface ApiAdminSubmissionsRouteChildren {
  ApiAdminSubmissionsIdRoute: typeof ApiAdminSubmissionsIdRoute
}

const ApiAdminSubmissionsRouteChildren: ApiAdminSubmissionsRouteChildren = {
  ApiAdminSubmissionsIdRoute: ApiAdminSubmissionsIdRoute,
}

const ApiAdminSubmissionsRouteWithChildren =
  ApiAdminSubmissionsRoute._addFileChildren(ApiAdminSubmissionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  FinishingRoute: FinishingRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  SubmitRoute: SubmitRoute,
  AdminDailyRoute: AdminDailyRoute,
  AdminLevelsRoute: AdminLevelsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminXpRoute: AdminXpRoute,
  CSlugRoute: CSlugRoute,
  IHandleRoute: IHandleRoute,
  UHandleRoute: UHandleRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminArtistsRoute: ApiAdminArtistsRouteWithChildren,
  ApiAdminBarsRoute: ApiAdminBarsRouteWithChildren,
  ApiAdminDailyRoute: ApiAdminDailyRouteWithChildren,
  ApiAdminLevelsRoute: ApiAdminLevelsRoute,
  ApiAdminPingRoute: ApiAdminPingRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRouteWithChildren,
  ApiAdminTagsRoute: ApiAdminTagsRoute,
  ApiAdminXpConfigRoute: ApiAdminXpConfigRoute,
  ApiAdminSearchArtistsRoute: ApiAdminSearchArtistsRoute,
  ApiAdminSearchTracksRoute: ApiAdminSearchTracksRoute,
  ApiAdminSongsIdRoute: ApiAdminSongsIdRoute,
  ApiAdminSearchTrackIdRoute: ApiAdminSearchTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
