/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminPingRouteImport } from './routes/api/admin/ping'
import { Route as ApiAdminBarsRouteImport } from './routes/api/admin/bars'
import { Route as ApiAdminArtistsRouteImport } from './routes/api/admin/artists'
import { Route as ApiAdminSongsIdRouteImport } from './routes/api/admin/songs.$id'
import { Route as ApiAdminBarsIdRouteImport } from './routes/api/admin/bars.$id'
import { Route as ApiAdminArtistsIdRouteImport } from './routes/api/admin/artists.$id'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPingRoute = ApiAdminPingRouteImport.update({
  id: '/api/admin/ping',
  path: '/api/admin/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBarsRoute = ApiAdminBarsRouteImport.update({
  id: '/api/admin/bars',
  path: '/api/admin/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtistsRoute = ApiAdminArtistsRouteImport.update({
  id: '/api/admin/artists',
  path: '/api/admin/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSongsIdRoute = ApiAdminSongsIdRouteImport.update({
  id: '/api/admin/songs/$id',
  path: '/api/admin/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBarsIdRoute = ApiAdminBarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBarsRoute,
} as any)
const ApiAdminArtistsIdRoute = ApiAdminArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRoute
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRoute
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRoute
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/songs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play'
    | '/admin/login'
    | '/admin'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/songs/$id'
  id:
    | '__root__'
    | '/'
    | '/play'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/songs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRoute: typeof PlayRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminArtistsRoute: typeof ApiAdminArtistsRouteWithChildren
  ApiAdminBarsRoute: typeof ApiAdminBarsRouteWithChildren
  ApiAdminPingRoute: typeof ApiAdminPingRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminSongsIdRoute: typeof ApiAdminSongsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ping': {
      id: '/api/admin/ping'
      path: '/api/admin/ping'
      fullPath: '/api/admin/ping'
      preLoaderRoute: typeof ApiAdminPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bars': {
      id: '/api/admin/bars'
      path: '/api/admin/bars'
      fullPath: '/api/admin/bars'
      preLoaderRoute: typeof ApiAdminBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artists': {
      id: '/api/admin/artists'
      path: '/api/admin/artists'
      fullPath: '/api/admin/artists'
      preLoaderRoute: typeof ApiAdminArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/songs/$id': {
      id: '/api/admin/songs/$id'
      path: '/api/admin/songs/$id'
      fullPath: '/api/admin/songs/$id'
      preLoaderRoute: typeof ApiAdminSongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bars/$id': {
      id: '/api/admin/bars/$id'
      path: '/$id'
      fullPath: '/api/admin/bars/$id'
      preLoaderRoute: typeof ApiAdminBarsIdRouteImport
      parentRoute: typeof ApiAdminBarsRoute
    }
    '/api/admin/artists/$id': {
      id: '/api/admin/artists/$id'
      path: '/$id'
      fullPath: '/api/admin/artists/$id'
      preLoaderRoute: typeof ApiAdminArtistsIdRouteImport
      parentRoute: typeof ApiAdminArtistsRoute
    }
  }
}

interface ApiAdminArtistsRouteChildren {
  ApiAdminArtistsIdRoute: typeof ApiAdminArtistsIdRoute
}

const ApiAdminArtistsRouteChildren: ApiAdminArtistsRouteChildren = {
  ApiAdminArtistsIdRoute: ApiAdminArtistsIdRoute,
}

const ApiAdminArtistsRouteWithChildren = ApiAdminArtistsRoute._addFileChildren(
  ApiAdminArtistsRouteChildren,
)

interface ApiAdminBarsRouteChildren {
  ApiAdminBarsIdRoute: typeof ApiAdminBarsIdRoute
}

const ApiAdminBarsRouteChildren: ApiAdminBarsRouteChildren = {
  ApiAdminBarsIdRoute: ApiAdminBarsIdRoute,
}

const ApiAdminBarsRouteWithChildren = ApiAdminBarsRoute._addFileChildren(
  ApiAdminBarsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRoute: PlayRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminArtistsRoute: ApiAdminArtistsRouteWithChildren,
  ApiAdminBarsRoute: ApiAdminBarsRouteWithChildren,
  ApiAdminPingRoute: ApiAdminPingRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminSongsIdRoute: ApiAdminSongsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
