/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as FinishingRouteImport } from './routes/finishing'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminReviewRouteImport } from './routes/admin/review'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDailyRouteImport } from './routes/admin/daily'
import { Route as ApiAdminTagsRouteImport } from './routes/api/admin/tags'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminPingRouteImport } from './routes/api/admin/ping'
import { Route as ApiAdminDailyRouteImport } from './routes/api/admin/daily'
import { Route as ApiAdminBarsRouteImport } from './routes/api/admin/bars'
import { Route as ApiAdminArtistsRouteImport } from './routes/api/admin/artists'
import { Route as ApiAdminSongsIdRouteImport } from './routes/api/admin/songs.$id'
import { Route as ApiAdminSearchTracksRouteImport } from './routes/api/admin/search.tracks'
import { Route as ApiAdminSearchArtistsRouteImport } from './routes/api/admin/search.artists'
import { Route as ApiAdminDailyIdRouteImport } from './routes/api/admin/daily.$id'
import { Route as ApiAdminBarsIdRouteImport } from './routes/api/admin/bars.$id'
import { Route as ApiAdminArtistsIdRouteImport } from './routes/api/admin/artists.$id'
import { Route as ApiAdminSearchTrackIdRouteImport } from './routes/api/admin/search.track.$id'
import { Route as ApiAdminArtistsIdTagsRouteImport } from './routes/api/admin/artists.$id.tags'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishingRoute = FinishingRouteImport.update({
  id: '/finishing',
  path: '/finishing',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailyRoute = AdminDailyRouteImport.update({
  id: '/admin/daily',
  path: '/admin/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTagsRoute = ApiAdminTagsRouteImport.update({
  id: '/api/admin/tags',
  path: '/api/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPingRoute = ApiAdminPingRouteImport.update({
  id: '/api/admin/ping',
  path: '/api/admin/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDailyRoute = ApiAdminDailyRouteImport.update({
  id: '/api/admin/daily',
  path: '/api/admin/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBarsRoute = ApiAdminBarsRouteImport.update({
  id: '/api/admin/bars',
  path: '/api/admin/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtistsRoute = ApiAdminArtistsRouteImport.update({
  id: '/api/admin/artists',
  path: '/api/admin/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSongsIdRoute = ApiAdminSongsIdRouteImport.update({
  id: '/api/admin/songs/$id',
  path: '/api/admin/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSearchTracksRoute = ApiAdminSearchTracksRouteImport.update({
  id: '/api/admin/search/tracks',
  path: '/api/admin/search/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSearchArtistsRoute = ApiAdminSearchArtistsRouteImport.update({
  id: '/api/admin/search/artists',
  path: '/api/admin/search/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDailyIdRoute = ApiAdminDailyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminDailyRoute,
} as any)
const ApiAdminBarsIdRoute = ApiAdminBarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBarsRoute,
} as any)
const ApiAdminArtistsIdRoute = ApiAdminArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminArtistsRoute,
} as any)
const ApiAdminSearchTrackIdRoute = ApiAdminSearchTrackIdRouteImport.update({
  id: '/api/admin/search/track/$id',
  path: '/api/admin/search/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtistsIdTagsRoute = ApiAdminArtistsIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ApiAdminArtistsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/play': typeof PlayRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/play': typeof PlayRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/finishing': typeof FinishingRoute
  '/play': typeof PlayRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/artists': typeof ApiAdminArtistsRouteWithChildren
  '/api/admin/bars': typeof ApiAdminBarsRouteWithChildren
  '/api/admin/daily': typeof ApiAdminDailyRouteWithChildren
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/tags': typeof ApiAdminTagsRoute
  '/api/admin/artists/$id': typeof ApiAdminArtistsIdRouteWithChildren
  '/api/admin/bars/$id': typeof ApiAdminBarsIdRoute
  '/api/admin/daily/$id': typeof ApiAdminDailyIdRoute
  '/api/admin/search/artists': typeof ApiAdminSearchArtistsRoute
  '/api/admin/search/tracks': typeof ApiAdminSearchTracksRoute
  '/api/admin/songs/$id': typeof ApiAdminSongsIdRoute
  '/api/admin/artists/$id/tags': typeof ApiAdminArtistsIdTagsRoute
  '/api/admin/search/track/$id': typeof ApiAdminSearchTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/finishing'
    | '/play'
    | '/admin/daily'
    | '/admin/login'
    | '/admin/review'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/tags'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/finishing'
    | '/play'
    | '/admin/daily'
    | '/admin/login'
    | '/admin/review'
    | '/admin'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/tags'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/finishing'
    | '/play'
    | '/admin/daily'
    | '/admin/login'
    | '/admin/review'
    | '/admin/'
    | '/api/admin/artists'
    | '/api/admin/bars'
    | '/api/admin/daily'
    | '/api/admin/ping'
    | '/api/admin/session'
    | '/api/admin/tags'
    | '/api/admin/artists/$id'
    | '/api/admin/bars/$id'
    | '/api/admin/daily/$id'
    | '/api/admin/search/artists'
    | '/api/admin/search/tracks'
    | '/api/admin/songs/$id'
    | '/api/admin/artists/$id/tags'
    | '/api/admin/search/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  FinishingRoute: typeof FinishingRoute
  PlayRoute: typeof PlayRoute
  AdminDailyRoute: typeof AdminDailyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminArtistsRoute: typeof ApiAdminArtistsRouteWithChildren
  ApiAdminBarsRoute: typeof ApiAdminBarsRouteWithChildren
  ApiAdminDailyRoute: typeof ApiAdminDailyRouteWithChildren
  ApiAdminPingRoute: typeof ApiAdminPingRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminTagsRoute: typeof ApiAdminTagsRoute
  ApiAdminSearchArtistsRoute: typeof ApiAdminSearchArtistsRoute
  ApiAdminSearchTracksRoute: typeof ApiAdminSearchTracksRoute
  ApiAdminSongsIdRoute: typeof ApiAdminSongsIdRoute
  ApiAdminSearchTrackIdRoute: typeof ApiAdminSearchTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finishing': {
      id: '/finishing'
      path: '/finishing'
      fullPath: '/finishing'
      preLoaderRoute: typeof FinishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily': {
      id: '/admin/daily'
      path: '/admin/daily'
      fullPath: '/admin/daily'
      preLoaderRoute: typeof AdminDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tags': {
      id: '/api/admin/tags'
      path: '/api/admin/tags'
      fullPath: '/api/admin/tags'
      preLoaderRoute: typeof ApiAdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ping': {
      id: '/api/admin/ping'
      path: '/api/admin/ping'
      fullPath: '/api/admin/ping'
      preLoaderRoute: typeof ApiAdminPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/daily': {
      id: '/api/admin/daily'
      path: '/api/admin/daily'
      fullPath: '/api/admin/daily'
      preLoaderRoute: typeof ApiAdminDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bars': {
      id: '/api/admin/bars'
      path: '/api/admin/bars'
      fullPath: '/api/admin/bars'
      preLoaderRoute: typeof ApiAdminBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artists': {
      id: '/api/admin/artists'
      path: '/api/admin/artists'
      fullPath: '/api/admin/artists'
      preLoaderRoute: typeof ApiAdminArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/songs/$id': {
      id: '/api/admin/songs/$id'
      path: '/api/admin/songs/$id'
      fullPath: '/api/admin/songs/$id'
      preLoaderRoute: typeof ApiAdminSongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/search/tracks': {
      id: '/api/admin/search/tracks'
      path: '/api/admin/search/tracks'
      fullPath: '/api/admin/search/tracks'
      preLoaderRoute: typeof ApiAdminSearchTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/search/artists': {
      id: '/api/admin/search/artists'
      path: '/api/admin/search/artists'
      fullPath: '/api/admin/search/artists'
      preLoaderRoute: typeof ApiAdminSearchArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/daily/$id': {
      id: '/api/admin/daily/$id'
      path: '/$id'
      fullPath: '/api/admin/daily/$id'
      preLoaderRoute: typeof ApiAdminDailyIdRouteImport
      parentRoute: typeof ApiAdminDailyRoute
    }
    '/api/admin/bars/$id': {
      id: '/api/admin/bars/$id'
      path: '/$id'
      fullPath: '/api/admin/bars/$id'
      preLoaderRoute: typeof ApiAdminBarsIdRouteImport
      parentRoute: typeof ApiAdminBarsRoute
    }
    '/api/admin/artists/$id': {
      id: '/api/admin/artists/$id'
      path: '/$id'
      fullPath: '/api/admin/artists/$id'
      preLoaderRoute: typeof ApiAdminArtistsIdRouteImport
      parentRoute: typeof ApiAdminArtistsRoute
    }
    '/api/admin/search/track/$id': {
      id: '/api/admin/search/track/$id'
      path: '/api/admin/search/track/$id'
      fullPath: '/api/admin/search/track/$id'
      preLoaderRoute: typeof ApiAdminSearchTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artists/$id/tags': {
      id: '/api/admin/artists/$id/tags'
      path: '/tags'
      fullPath: '/api/admin/artists/$id/tags'
      preLoaderRoute: typeof ApiAdminArtistsIdTagsRouteImport
      parentRoute: typeof ApiAdminArtistsIdRoute
    }
  }
}

interface ApiAdminArtistsIdRouteChildren {
  ApiAdminArtistsIdTagsRoute: typeof ApiAdminArtistsIdTagsRoute
}

const ApiAdminArtistsIdRouteChildren: ApiAdminArtistsIdRouteChildren = {
  ApiAdminArtistsIdTagsRoute: ApiAdminArtistsIdTagsRoute,
}

const ApiAdminArtistsIdRouteWithChildren =
  ApiAdminArtistsIdRoute._addFileChildren(ApiAdminArtistsIdRouteChildren)

interface ApiAdminArtistsRouteChildren {
  ApiAdminArtistsIdRoute: typeof ApiAdminArtistsIdRouteWithChildren
}

const ApiAdminArtistsRouteChildren: ApiAdminArtistsRouteChildren = {
  ApiAdminArtistsIdRoute: ApiAdminArtistsIdRouteWithChildren,
}

const ApiAdminArtistsRouteWithChildren = ApiAdminArtistsRoute._addFileChildren(
  ApiAdminArtistsRouteChildren,
)

interface ApiAdminBarsRouteChildren {
  ApiAdminBarsIdRoute: typeof ApiAdminBarsIdRoute
}

const ApiAdminBarsRouteChildren: ApiAdminBarsRouteChildren = {
  ApiAdminBarsIdRoute: ApiAdminBarsIdRoute,
}

const ApiAdminBarsRouteWithChildren = ApiAdminBarsRoute._addFileChildren(
  ApiAdminBarsRouteChildren,
)

interface ApiAdminDailyRouteChildren {
  ApiAdminDailyIdRoute: typeof ApiAdminDailyIdRoute
}

const ApiAdminDailyRouteChildren: ApiAdminDailyRouteChildren = {
  ApiAdminDailyIdRoute: ApiAdminDailyIdRoute,
}

const ApiAdminDailyRouteWithChildren = ApiAdminDailyRoute._addFileChildren(
  ApiAdminDailyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  FinishingRoute: FinishingRoute,
  PlayRoute: PlayRoute,
  AdminDailyRoute: AdminDailyRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminArtistsRoute: ApiAdminArtistsRouteWithChildren,
  ApiAdminBarsRoute: ApiAdminBarsRouteWithChildren,
  ApiAdminDailyRoute: ApiAdminDailyRouteWithChildren,
  ApiAdminPingRoute: ApiAdminPingRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminTagsRoute: ApiAdminTagsRoute,
  ApiAdminSearchArtistsRoute: ApiAdminSearchArtistsRoute,
  ApiAdminSearchTracksRoute: ApiAdminSearchTracksRoute,
  ApiAdminSongsIdRoute: ApiAdminSongsIdRoute,
  ApiAdminSearchTrackIdRoute: ApiAdminSearchTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
